import {
  defineConfig,
  globalIgnores,
} from "eslint/config";

import nextVitals from "eslint-config-next/core-web-vitals";

import nextTs from "eslint-config-next/typescript";


export default defineConfig([
  ...nextVitals,

  ...nextTs,


  /*
   * Files generated by frameworks,
   * Python virtual environments,
   * datasets and build tooling must
   * never enter the frontend ESLint
   * scope.
   */
  globalIgnores([
    ".next/**",

    "out/**",

    "build/**",

    "dist/**",

    "coverage/**",

    "node_modules/**",

    "**/.venv/**",

    "**/venv/**",

    "research/**/.venv/**",

    "next-env.d.ts",
  ]),


  /*
   * MicroscopePrototype is currently
   * intentionally frozen while the
   * scientific processing pipeline is
   * being moved behind isolated service
   * boundaries.
   *
   * It predates the newer React hooks
   * lint rules below and uses refs for
   * realtime microscope telemetry.
   *
   * Keep the new rules enabled for the
   * rest of the application while
   * temporarily excluding only this
   * legacy workstation component.
   */
  {
    files: [
      "src/components/MicroscopePrototype.tsx",
    ],

    rules: {
      "react-hooks/set-state-in-effect":
        "off",

      "react-hooks/refs":
        "off",
    },
  },
]);